USE [master]
GO
/****** Object:  Database [School_DB]    Script Date: 1/13/2021 9:42:36 PM ******/
CREATE DATABASE [School_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'School_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\School_DB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'School_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\School_DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [School_DB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [School_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [School_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [School_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [School_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [School_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [School_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [School_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [School_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [School_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [School_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [School_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [School_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [School_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [School_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [School_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [School_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [School_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [School_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [School_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [School_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [School_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [School_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [School_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [School_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [School_DB] SET  MULTI_USER 
GO
ALTER DATABASE [School_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [School_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [School_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [School_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [School_DB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'School_DB', N'ON'
GO
USE [School_DB]
GO
/****** Object:  Table [dbo].[branch]    Script Date: 1/13/2021 9:42:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[branch](
	[branch_id] [int] NOT NULL,
	[branch_name] [varchar](40) NULL,
	[mgr_id] [int] NULL,
	[mgr_start_date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[branch_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[client]    Script Date: 1/13/2021 9:42:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[client](
	[client_id] [int] NOT NULL,
	[client_name] [varchar](40) NULL,
	[branch_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[client_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[employee]    Script Date: 1/13/2021 9:42:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[employee](
	[emp_id] [int] NOT NULL,
	[first_name] [varchar](40) NULL,
	[last_name] [varchar](40) NULL,
	[birth_day] [date] NULL,
	[salary] [int] NULL,
	[super_id] [int] NULL,
	[branch_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[emp_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[branch]  WITH CHECK ADD FOREIGN KEY([mgr_id])
REFERENCES [dbo].[employee] ([emp_id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[client]  WITH CHECK ADD FOREIGN KEY([branch_id])
REFERENCES [dbo].[branch] ([branch_id])
GO
ALTER TABLE [dbo].[employee]  WITH CHECK ADD FOREIGN KEY([branch_id])
REFERENCES [dbo].[branch] ([branch_id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[employee]  WITH CHECK ADD FOREIGN KEY([branch_id])
REFERENCES [dbo].[branch] ([branch_id])
GO
ALTER TABLE [dbo].[employee]  WITH CHECK ADD FOREIGN KEY([super_id])
REFERENCES [dbo].[employee] ([emp_id])
GO
USE [master]
GO
ALTER DATABASE [School_DB] SET  READ_WRITE 
GO
